app = "canting-demo"
primary_region = "iad"

[env]
TZ = "Africa/Cairo"
PORT = "3000"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 3_000
min_machines_running = 0
processes = [ "app" ]

[[mounts]]
auto_extend_size_increment = "1GB"
auto_extend_size_limit = "10GB"
auto_extend_size_threshold = 80
destination = "/data"
source = "data"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "256mb"
